DROP DATABASE IF EXISTS practica1;
GO
CREATE DATABASE practica1;
GO
USE practica1;
CREATE TABLE ARTICULOS(
IDART INT NOT NULL,
[DESC] CHAR(50) NULL,
PESO DECIMAL(10,2) NULL,
COLOR CHAR(20) NULL,
CIUDAD CHAR(60) NULL,
CONSTRAINT PK_ARTICULOS PRIMARY KEY (IDART)
);
CREATE TABLE PROVEEDORES(
IDPROV INT NOT NULL,
NOMBRE CHAR(60) NULL,
CATEGORIA INT NULL,
CIUDAD CHAR(60) NULL,
CONSTRAINT PK_PROVEEDORES PRIMARY KEY
(IDPROV)
);
CREATE TABLE CONTRATOS(
IDPROV int NOT NULL,
IDART int NOT NULL,
CANT int NULL,
CONSTRAINT PK_CONTRATOS PRIMARY KEY
(IDPROV, IDART),
CONSTRAINT FK_CONTRATOS_ARTICULOS FOREIGN
KEY(IDART) REFERENCES ARTICULOS (IDART),
CONSTRAINT FK_CONTRATOS_PROVEEDORES FOREIGN
KEY(IDPROV) REFERENCES PROVEEDORES (IDPROV)
);
GO
INSERT ARTICULOS (IDART, [DESC], PESO,
COLOR, CIUDAD) VALUES (10, 'A', 5, 'Rojo',
'Jujuy')
INSERT ARTICULOS (IDART, [DESC], PESO,
COLOR, CIUDAD) VALUES (20, 'F', 7, 'Rojo',
'Rosario')
INSERT ARTICULOS (IDART, [DESC], PESO,
COLOR, CIUDAD) VALUES (30, 'A', 5, 'Azul',
'Córdoba')
INSERT ARTICULOS (IDART, [DESC], PESO,
COLOR, CIUDAD) VALUES (40, 'Z', 3, 'Verde',
'Córdoba')
INSERT ARTICULOS (IDART, [DESC], PESO,
COLOR, CIUDAD) VALUES (50, 'C', 1, 'Verde',
'Rosario')
INSERT ARTICULOS (IDART, [DESC], PESO,
COLOR, CIUDAD) VALUES (60, 'W', 9, 'Rojo',
'Córdoba')
INSERT PROVEEDORES (IDPROV, NOMBRE,
CATEGORIA, CIUDAD) VALUES (1, 'Jaime', 20,
'Córdoba')
INSERT PROVEEDORES (IDPROV, NOMBRE,
CATEGORIA, CIUDAD) VALUES (3, 'ACME', 30,
'Rosario')
INSERT PROVEEDORES (IDPROV, NOMBRE,
CATEGORIA, CIUDAD) VALUES (4, 'González',
10, 'Rosario')
INSERT PROVEEDORES (IDPROV, NOMBRE,
CATEGORIA, CIUDAD) VALUES (5, 'XXX', 10,
'Trelew')
INSERT PROVEEDORES (IDPROV, NOMBRE,
CATEGORIA, CIUDAD) VALUES (6, 'Celia', 20,
'Córdoba')
INSERT CONTRATOS (IDPROV, IDART, CANT)
VALUES (1, 10, 300)
INSERT CONTRATOS (IDPROV, IDART, CANT)
VALUES (1, 30, 200)
INSERT CONTRATOS (IDPROV, IDART, CANT)
VALUES (1, 40, 100)
INSERT CONTRATOS (IDPROV, IDART, CANT)
VALUES (1, 50, 400)
INSERT CONTRATOS (IDPROV, IDART, CANT)
VALUES (1, 60, 200)
INSERT CONTRATOS (IDPROV, IDART, CANT)
VALUES (3, 10, 150)
INSERT CONTRATOS (IDPROV, IDART, CANT)
VALUES (3, 20, 200)
INSERT CONTRATOS (IDPROV, IDART, CANT)
VALUES (3, 60, 200)
INSERT CONTRATOS (IDPROV, IDART, CANT)
VALUES (4, 10, 100)
INSERT CONTRATOS (IDPROV, IDART, CANT)
VALUES (4, 20, 300)
INSERT CONTRATOS (IDPROV, IDART, CANT)
VALUES (4, 30, 400)
INSERT CONTRATOS (IDPROV, IDART, CANT)
VALUES (4, 60, 300)
INSERT CONTRATOS (IDPROV, IDART, CANT)
VALUES (6, 20, 100)